version: '3.2'

services:
    skeleton_redis:
      container_name: 'skeleton_redis'
      image: redis:latest
      ports:
        - 8002:6379
      restart: always


    skeleton_mysql:
      container_name: 'skeleton_mysql'
      image: mysql:5.7
      volumes:
        - ./run/var:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=skeleton
        - MYSQL_USER=skeleton
        - MYSQL_PASSWORD=1
      ports:
        - 8001:3306
      restart: always

      
    skeleton_app:
      container_name: 'skeleton'
      build:
        context: '.'
      volumes:
        - .:/var/www/html
      links:
        - 'skeleton_mysql'
        - 'skeleton_redis'
      depends_on:
        - 'skeleton_mysql'
        - 'skeleton_redis'
      ports:
        - 8000:80
      restart: always
