version: '3.2'

services:
    skeleton_redis:
      container_name: 'skeleton_redis'
      image: redis:latest
      networks:
        - backend
      ports:
        - "${REDIS_EXTERNAL_PORT}:${REDIS_PORT}"
      restart: always

    skeleton_mysql:
      container_name: 'skeleton_mysql'
      image: mysql:5.7
      volumes:
        - ./run/var:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
        - MYSQL_DATABASE=${DB_DATABASE}
        - MYSQL_USER=${DB_USERNAME}
        - MYSQL_PASSWORD=${DB_PASSWORD}
      networks:
        - backend
      ports:
        - "${MYSQL_EXTERNAL_PORT}:${DB_PORT}"
      restart: always

    skeleton_app:
      container_name: 'skeleton'
      volumes:
        - ../:/var/www/html/
        - ./.env:/var/www/html/.env
      build:
        context: './'
        dockerfile: './app/dockerfile'
      depends_on:
        - 'skeleton_mysql'
        - 'skeleton_redis'
      networks:
        - backend
      restart: always
      
    skeleton_apache:
      container_name: 'skeleton_apache'
      volumes:
        - ../:/var/www/html/
        - ./.env:/var/www/html/.env
      build:
        context: './'
        dockerfile: './apache/dockerfile'
      depends_on:
        - skeleton_app
      networks:
        - backend
      ports:
        - "${APACHE_EXTERNAL_PORT}:${APACHE_PORT}"
      restart: always

    skeleton_echo:
      container_name: 'skeleton_echo'
      volumes:
        - ../:/var/www/html/
        - ./.env:/var/www/html/.env
      build:
        context: './'
        dockerfile: './echo/dockerfile'
      depends_on:
        - skeleton_app
        - skeleton_redis
      networks:
        - backend
      ports:
        - "${LARAVEL_ECHO_EXTERNAL_PORT}:${LARAVEL_ECHO_SERVER_PORT}"
      restart: always

networks:
  backend: