version: '3.2'

services:
    abaza_redis:
      container_name: 'abaza_redis'
      image: redis:latest
      networks:
        - backend
      ports:
        - "${REDIS_EXTERNAL_PORT}:${REDIS_PORT}"
      restart: always

    abaza_mysql:
      container_name: 'abaza_mysql'
      image: mysql:5.7
      volumes:
        - ./run/var:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
        - MYSQL_DATABASE=${DB_DATABASE}
        - MYSQL_USER=${DB_USERNAME}
        - MYSQL_PASSWORD=${DB_PASSWORD}
      networks:
        - backend
      ports:
        - "${MYSQL_EXTERNAL_PORT}:${DB_PORT}"
      restart: always

    abaza_app:
      container_name: 'abaza'
      volumes:
        - ../:/var/www/html/
        - ../.env:/var/www/html/.env
      build:
        context: './'
        dockerfile: './app/dockerfile'
      depends_on:
        - 'abaza_mysql'
        - 'abaza_redis'
      networks:
        - backend
      restart: always
      
    abaza_apache:
      container_name: 'abaza_apache'
      volumes:
        - ../:/var/www/html/
        - ../.env:/var/www/html/.env
      build:
        context: './'
        dockerfile: './apache/dockerfile'
      depends_on:
        - abaza_app
      networks:
        - backend
      ports:
        - "${APACHE_EXTERNAL_PORT}:${APACHE_PORT}"
      restart: always

networks:
  backend: